#version 100
// Adapted from user-provided Phigros 4.0.1 APK, Unlit/DisabledBlock.
// Generated by scripts/port-block-shaders.py; constants are from sharedassets12.
precision highp float;
precision highp int;
varying highp vec2 uv;
uniform vec2 sceneScale;
uniform vec2 sceneOffset;
uniform vec4 blockTime;
const vec4 _FillColor = vec4(0.4970000088214874, 0.13766898214817047, 0.13766898214817047, 1.0);
const float _FillOpacity = 0.4000000059604645;
const vec3 _SparkTint = vec3(0.31132078170776367, 0.07783019542694092, 0.07783019542694092);
const float _SparkMapOpacity = 3.5;
const float _SparkDisplaceIntensity = 2.2899999618530273;
const float _DisplaceSpeed = 0.30000001192092896;
const vec4 _DisplaceDirection = vec4(1.0, 1.0, 0.0, 0.0);
uniform mediump sampler2D _ComposeRT;
uniform mediump sampler2D _DisplaceMap;
uniform mediump sampler2D _SparkMap;

mediump float u_xlat16_0;
mediump vec3 u_xlat16_1;
vec4 u_xlat2;
mediump float u_xlat16_3;
vec3 u_xlat4;
mediump float u_xlat16_4;
bool u_xlatb4;
mediump float u_xlat16_8;
mediump float u_xlat16_9;
mediump float u_xlat16_13;
void main()
{
    u_xlat16_0 = texture2D(_ComposeRT, (uv).xy).x;
    u_xlat16_1.x = u_xlat16_0 + -9.99999975e-05;
    u_xlatb4 = u_xlat16_1.x<0.0;
    if(u_xlatb4){discard;}
    u_xlat4.x = blockTime.x * _DisplaceSpeed;
    u_xlat16_1.x = dot(_DisplaceDirection.xy, _DisplaceDirection.xy);
    u_xlat16_1.x = inversesqrt(u_xlat16_1.x);
    u_xlat16_1.xy = u_xlat16_1.xx * _DisplaceDirection.xy;
    u_xlat2.xyw = u_xlat4.xxx * u_xlat16_1.xyx;
    u_xlat2.z = u_xlat4.x * (-u_xlat16_1.y);
    u_xlat2 = u_xlat2 + ((uv * vec2(0.5, 0.20000000298023224) + vec2(0.0, 0.0))).xyxy;
    u_xlat16_4 = texture2D(_DisplaceMap, u_xlat2.zw).x;
    u_xlat16_8 = texture2D(_DisplaceMap, u_xlat2.xy).x;
    u_xlat16_9 = u_xlat16_4 + -0.5;
    u_xlat16_13 = u_xlat16_4 + u_xlat16_8;
    u_xlat16_3 = u_xlat16_8 + -0.5;
    u_xlat16_13 = u_xlat16_13 * 0.5;
    u_xlat2.x = u_xlat16_9 * (-u_xlat16_1.y);
    u_xlat2.y = u_xlat16_9 * u_xlat16_1.x;
    u_xlat4.xy = u_xlat16_1.xy * vec2(u_xlat16_3) + u_xlat2.xy;
    u_xlat4.xy = u_xlat4.xy * vec2(_SparkDisplaceIntensity) + ((uv * vec2(3.0, 1.2000000476837158) + vec2(0.0, 0.0))).xy;
    u_xlat16_4 = texture2D(_SparkMap, u_xlat4.xy).x;
    u_xlat4.xyz = vec3(u_xlat16_4) * _SparkTint.xyz;
    u_xlat4.xyz = vec3(u_xlat16_13) * u_xlat4.xyz;
    u_xlat16_1.xyz = _FillColor.xyz * vec3(_FillOpacity);
    u_xlat16_1.xyz = u_xlat4.xyz * vec3(_SparkMapOpacity) + u_xlat16_1.xyz;
    gl_FragColor.xyz = vec3(u_xlat16_0) * u_xlat16_1.xyz;
    gl_FragColor.w = (vec4(1.0)).w;
    return;
}

