"""Adapt extracted GLES programs to Phira; retain APK material constants."""
import argparse, pathlib, re, json, shutil
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('input', type=pathlib.Path, help='Unity export directory from extract-block-area.py')
parser.add_argument('--output', type=pathlib.Path, default=pathlib.Path(__file__).resolve().parents[1] / 'prpr/src/core/shaders/block_area')
args = parser.parse_args()
src, dst = args.input, args.output
dst.mkdir(parents=True, exist_ok=True)
for number, name, mat in [(38, 'ActiveBlock', 5), (39, 'DisabledBlock', 8)]:
    text = (src / f'sharedassets12.assets_{number}_Unlit_{name}.glsl').read_text()
    text = text.split('#ifdef FRAGMENT\n', 1)[1].rsplit('#endif', 1)[0]
    text = text[text.index('uniform \tvec4 _Time;'):]
    props = json.loads((src / f'sharedassets12.assets_{mat}_{name}.json').read_text())['m_SavedProperties']
    floats = dict(props['m_Floats'])
    colors = dict(props['m_Colors'])
    tex = dict(props['m_TexEnvs'])
    dynamic = {'_Time', '_ScreenParams', '_EffectRT_TexelSize', '_TouchPosCount', '_TouchPosShine'}
    def decl(m):
        kind, key = m.group(1), m.group(2)
        if key in dynamic:
            return f'uniform {kind} {key};'
        if kind == 'float':
            return f'const float {key} = {float(floats[key])};'
        if kind.startswith('vec'):
            vals = [colors[key][c] for c in 'rgba'][:int(kind[-1])]
            return f'const {kind} {key} = {kind}({", ".join(str(float(v)) for v in vals)});'
        raise ValueError((kind, key))
    text = re.sub(r'uniform\s+(?:mediump\s+)?(float|int|vec[234])\s+(\w+);', decl, text)
    text = re.sub(r'UNITY_LOCATION\(\d+\)\s*', '', text)
    text = re.sub(r'in highp .*?;\n', '', text)
    text = re.sub(r'layout\(location = 0\) out mediump vec4 SV_Target0;', '', text)
    text = text.replace('SV_Target0', 'gl_FragColor')
    text = text.replace('uniform mediump sampler2D _TouchDisplaceMap;', '')
    text = text.replace('_TouchDisplaceMap,', '_DisplaceMap,')
    text = re.sub(r'textureLod\((\w+), ([^,]+), 0\.0\)', r'texture2D(\1, \2)', text)
    text = text.replace('texture(', 'texture2D(')
    text = text.replace('uniform \tvec2 _TouchPos[10];', '\n'.join(f'uniform vec2 touch{i};' for i in range(10)) + '\nvec2 touchAt(int i) {\n' + '\n'.join(f'    if (i == {i}) return touch{i};' for i in range(9)) + '\n    return touch9;\n}')
    text = re.sub(r'_TouchPos\[([^]]+)\]', r'touchAt(\1)', text)
    mapping = {'vs_TEXCOORD0': 'uv', 'vs_COLOR0': 'vec4(1.0)', 'vs_TEXCOORD3': 'vec4(uv, 0.0, 1.0)', 'vs_TEXCOORD6': '0.5'}
    coord_names = {'vs_TEXCOORD1': '_DisplaceMap', 'vs_TEXCOORD2': '_SparkMap', 'vs_TEXCOORD4': '_TouchDisplaceMap', 'vs_TEXCOORD5': '_NoiseMap'} if name == 'ActiveBlock' else {'vs_TEXCOORD2': '_DisplaceMap', 'vs_TEXCOORD3': '_SparkMap'}
    for key, value in coord_names.items():
        entry = tex[value]
        scale, offset = entry['m_Scale'], entry['m_Offset']
        mapping[key] = f'(uv * vec2({float(scale["x"])}, {float(scale["y"])}) + vec2({float(offset["x"])}, {float(offset["y"])}))'
    for key, value in mapping.items():
        text = re.sub(r'\b' + key + r'\b', '(' + value + ')', text)
    text = re.sub(r'texture2D\(_SceneColor, ([^)]+)\)', r'texture2D(_SceneColor, (\1) * sceneScale + sceneOffset)', text)
    # Macroquad always overwrites its built-in _Time with (t, sin(t), cos(t), 0).
    # Use a private name for Unity's (t/20, t, 2t, 3t) chart clock.
    text = re.sub(r'\b_Time\b', 'blockTime', text)
    # HLSLcc's loop is rewritten to a statically bounded GLES 2 loop.
    text = text.replace('for(', 'for (')
    header = '#version 100\n// Adapted from user-provided Phigros 4.0.1 APK, Unlit/' + name + '.\n// Generated by scripts/port-block-shaders.py; constants are from sharedassets12.\nprecision highp float;\nprecision highp int;\nvarying highp vec2 uv;\nuniform vec2 sceneScale;\nuniform vec2 sceneOffset;\n'
    (dst / ('active.glsl' if name == 'ActiveBlock' else 'disabled.glsl')).write_text(header + text, encoding='utf8')
for old, new in [('15_FD_Noise_00000.png','noise.png'), ('17_PointNoise.png','spark.png'), ('30_BlockNoise1.png','displace.png')]:
    shutil.copyfile(src / old, dst / new)
